### PR TITLE
Extract general API authentication logic to new django-moj-auth package

### PR DESCRIPTION
**Pull request by ibrechin**
In order to reuse the API authentication logic across multiple applications, the meat
of the mtp_auth app has been extracted into a resuable app. What remains is a layer
over the reusable app that specializes it for the mtp project.

See: https://github.com/ministryofjustice/django-moj-auth

### CODE REVIEW

**Comment by ibrechin** [comment]
@marcofucci obviously, currently this won't build as pip won't be able to install the new package, as it isn't uploaded anywhere. But take a look, see if you think I cut it off at the right level.

**Comment by marcofucci** [comment]
@ibrechin looks good.

Can we move the views there as well and have generic templates (or no templates at all)?
It seems that they are quite generic and it's better to avoid people from copying/pasting them in every project.

Also, until we are not happy to upload it to pipit you can pip from github

**Comment by SteveMarshall** [comment]
retest this please

**Comment by ibrechin** [comment]
@marcofucci yeh, first draft had the views split out as well, but I wasn't sure if custom templates might be a frequent requirement or not.

**Comment by marcofucci** [comment]
@ibrechin it's always possible to override the templates in the urls of your project so I think it should be fine.

**Comment by SteveMarshall** [comment]
> 20 additions and 834 deletions

:+1: LGTM. @marcofucci?

**Comment by marcofucci** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by marcofucci** [comment]
@ibrechin can I merge this?

**Comment by ibrechin** [comment]
@marcofucci yes, if you're happy with it

**Pull request merged**
