### PR TITLE
Make transaction history search form work via a GET request

### PR DESCRIPTION
**Pull request by ushkarev**
so that google analytics can be used to monitor search parameters such, particularly the text-based search

### CODE REVIEW

**Comment by maxf** [comment]
Can I suggest to make the URL nicer?
instead of :
?received_at_0=16%2F11%2F2015&received_at_1=23%2F11%2F2015&search=blah&owner=
better:
?from=20151116&to=20151120&search=blah&owner=me

**Comment by maxf** [comment]
Can you confirm that django prevents DOM/script injections from the query string params?

**Comment by ushkarev** [comment]
RE injection: django escapes all form values unless explicitly marked as safe

**Comment by ushkarev** [comment]
RE GET params: we can change `received_at_0` and `received_at_1` but the number following that depends on what's input into the form field. it'd be weird to make people type dates specifically as `20151116`… unless you set up a date picker and then pre-process the form on submission with JS

**Comment by maxf** [comment]
We can use tricks not to show the user confusing date formats on the form
while having them in the URL, but let's not bother just yet.

**Comment by SteveMarshall** [comment]
In terms of the query string param formats, @ushkarev is right: we need a sensible format in the front-end. Ideally, something hyphen-separated (slashes get escaped in query strings).

I might also argue for `from` and `to` as the parameter names, rather than `since` and `until`, because they seem clearer? Or is there something I'm missing?

**Comment by ushkarev** [comment]
max and i were thinking that the date formatting is a slightly separate
issue which could go with the JS date picker task. the primary point of
this PR was to put the search text into the url for google analytics to
pick up.

**Comment by ushkarev** [comment]
as we were saying, `from` is a reserved keyword so it'd be overly hacky to
make it work.

**Pull request merged**
